vich_uploader:
    db_driver: orm

    mappings:
        pictures:
           uri_prefix: /uploads/product
           upload_destination: '%kernel.project_dir%/public/uploads/product'
           namer: Vich\UploaderBundle\Naming\OrignameNamer
