<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYZGeA29\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYZGeA29/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYZGeA29.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYZGeA29\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYZGeA29\App_KernelDevDebugContainer([
    'container.build_hash' => 'YZGeA29',
    'container.build_id' => '845c3089',
    'container.build_time' => 1633620886,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYZGeA29');
